# NumPy Fundamentals

### 1. Run the following cells:

In [1]:
import numpy as np

In [2]:
array_1D = np.array([10,11,12,13,14])
array_1D

array([10, 11, 12, 13, 14])

In [3]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [4]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

### 2. Display the first element (not necessarily individual element) for each of the 3 arrays we defined above.

In [11]:
array_1D[0]


10

In [12]:
array_2D[0]


array([20, 30, 40, 50, 60])

In [13]:
array_3D[0]

array([[ 1,  2,  3,  4,  5],
       [11, 21, 31, 41, 51]])

### 3. Call the first individual element of the each of the 3 arrays. 

In [15]:
array_1D[0]

10

In [16]:
array_2D[0,0]

20

In [18]:
array_3D[0,0,0]

1

### 4. Uses negative indices to display the last element of each array.

In [25]:
array_3D[-1]

array([[11, 12, 13, 14, 15],
       [51, 52, 53, 54,  5]])

In [26]:
array_2D[-1]

array([11, 22, 33, 44, 55])

In [27]:
array_1D[-1]

14

### 5. Set the penultimate (second-to-last) <i> individual </i> element of each array equal to 10. Then display the variables to check your work. 
(<b>Hint</b>: If it's the penultimate individual element of the 2-D/3-D array, it needs to be in the last row of the 2-D array)

In [28]:
array_1D[-2] = 10
array_1D

array([10, 11, 12, 10, 14])

In [33]:
array_2D[2,-2] = 10
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 10, 55]])

In [42]:
array_3D[1,1,-2] #to read 3d or more elements we set the first variable to be the 'sheet' of the operation which would be where we are looking at and after we do row, column
array_3D[1,1,-2] = 10
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 10,  5]]])

### 6. Set the last column of the 2-D array to 100. Then display the variables to check your work. 

In [45]:
array_2D[:, 4] = 100
array_2D

array([[ 20,  30,  40,  50, 100],
       [ 43,  54,  65,  76, 100],
       [ 11,  22,  33,  10, 100]])

### 7. Set all the values of the 3-D array to 1000. Then display the variables to check your work. 

In [47]:
array_3D[:] = 1000
array_3D

array([[[1000, 1000, 1000, 1000, 1000],
        [1000, 1000, 1000, 1000, 1000]],

       [[1000, 1000, 1000, 1000, 1000],
        [1000, 1000, 1000, 1000, 1000]]])

### 8. Run the next 3 cells to re-define the 3 arrays, since we altered their contents. 

In [48]:
array_1D = np.array([10,11,12,13,14])
array_1D

array([10, 11, 12, 13, 14])

In [49]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [50]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

### 9. Add 2 to every element of the 3 arrays without overwriting their values.

### 10. Multiply the values of each array by 100 without overwriting their values.

### 11. Add up <i>array_1D</i> and the first row of <i>array_2D</i>

### 12. Find the product of <i>array_1D</i> and the first row of <i>array_2D</i>

### 13. Find the product  of the first row of <i>array_2D</i> and the first row of the first array of <i> array_3D </i>

### 14. Subtract <i> array_1D </i> from the first row of <i>array_2D</i>

### 15. Subtract the first row of <i>array_2D</i> from  <i> array_1D </i> 

### 16. Alter the code in the next 3 cells to re-define the 3 arrays as the following datatypes:
    A) array_1D -> NumPy Strings
    B) array_2D -> Complex Numbers
    C) array_3D -> 64-bit Floats
    
   (<b>Hint</b>: The datatypes are the following: <i>np.str</i>, <i>np.complex</i>, <i>np.float64</i>)

In [ ]:
array_1D = np.array([10,11,12,13,14])
array_1D

In [ ]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

In [ ]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

### 17. Now run the next 3 cells to re-define the 3 arrays as 32-bit floats, since we want to run some more computations on them

In [ ]:
array_1D = np.array([10,11,12,13,14], dtype = np.float32)
array_1D

In [ ]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]], dtype = np.float32)
array_2D

In [ ]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]], dtype = np.float32)
array_3D

### 18. Use broadcasting to subtract  <i>array_1D</i> from every row of <i> array_2D </i> 
   (<b>Hint</b>: You **don't** need a function to do this.)

### 19. Use broadcasting to divide all rows of <i>array_3D</i> by <i> array_1D </i> 

### 19. Use broadcasting to find the product of all rows of <i>array_3D</i>  and the last row of <i> array_2D </i> 

### 20. Since these products are all integers, let's cast them as such
   (<b>Hint</b>: You can use the np.array() function here)

### 21. Let's use axis argument of the np.mean() function to find the mean for every column of the 2-D array

### 22. Let's use axis argument of the np.mean() function to find the mean for every column of the 3-D array
   (<b>Hint</b>: Make sure you define the correct axis.)